version: '3'

services:
  app:
    build:
      context: .
    container_name: laravel-docker
    image: laravel-app:latest
    ports:
      - "8000:80"   # Changer le port pour exposer sur le port 80
    volumes:
      - ./src:/var/www
    networks:
      - laravel-network
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: gestion_parcauto
      DB_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret
      
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      -  ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
    depends_on:
      - app

networks:
  laravel-network:
    driver: bridge
